{"report": {"environment": {"Python": "3.7.1", "Platform": "Darwin-17.4.0-x86_64-i386-64bit"}, "tests": [{"name": "result.py::TestExample::test_example_1", "duration": 0.046207427978515625, "run_index": 0, "setup": {"name": "setup", "duration": 0.022841215133666992, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0002880096435546875, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.00023698806762695312, "outcome": "passed"}, "outcome": "passed"}, {"name": "result.py::TestExample::test_example_2", "duration": 0.001271963119506836, "run_index": 1, "setup": {"name": "setup", "duration": 0.00028395652770996094, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0002319812774658203, "outcome": "failed", "longrepr": "self = <result.TestExample testMethod=test_example_2>\n\n    def test_example_2(self):\n>       self.assertTrue(False, 'example of failed test')\nE       AssertionError: False is not true : example of failed test\n\nresult.py:8: AssertionError"}, "teardown": {"name": "teardown", "duration": 0.00047206878662109375, "outcome": "passed"}, "outcome": "failed"}, {"name": "result.py::TestExample::test_example_3", "duration": 0.0016410350799560547, "run_index": 2, "setup": {"name": "setup", "duration": 0.0004706382751464844, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0002639293670654297, "outcome": "skipped", "longrepr": "('result.py', 9, 'Skipped: example of skipped test')"}, "teardown": {"name": "teardown", "duration": 0.00043582916259765625, "outcome": "passed"}, "outcome": "skipped"}], "summary": {"passed": 1, "failed": 1, "skipped": 1, "num_tests": 3, "duration": 0.12059211730957031}, "created_at": "2019-08-01 15:45:41.191654"}}